### PR TITLE
update ResourceLoader "add" method

### PR DESCRIPTION
**Pull request by mathieuanthoine**

### CODE REVIEW

**Comment by adireddy** [comment]
:+1:

**Comment by adireddy** [comment]
made a few changes, please have a look and let me know if I have missed anything.

**Comment by mathieuanthoine** [comment]
Sorry but I don't see where you have made some changes :/

**Comment by adireddy** [comment]
you need to look here :) https://github.com/pixijs/pixi-haxe/blob/master/pixi/loaders/ResourceLoader.hx

**Comment by mathieuanthoine** [comment]
ok thank you !
Perfect for me, check the new update of before method :)

**Pull request merged**
