### PR TITLE
CloudKidStudios PixiParticles wrappers

### PR DESCRIPTION
**Pull request by halfabench**
Hi,
I just finished to wrap all the classes for https://github.com/CloudKidStudio/PixiParticles.
The documentation is also up-to-date.

I have successfully used Emitter, Particle and ParticleUtils in two projects with haxe-pixi. 
However, I have not used AnimatedParticle and PathParticle yet. 

I have been following your package naming convention.
So package name is pixi.plugins.particle.

:)

### CODE REVIEW

**Comment by adireddy** [comment]
Great Work @halfabench  :+1: 

Can u raise the pull request to the develop branch please. I am keeping master in synch with haxelib release.

Also do you have any haxe samples that can demonstrate these features? Not a priority right now but it will be good if we can add them to the samples.

**Comment by halfabench** [comment]
ok. I'll try to do that. (not a git specialist myself so I imagine I have to make my changes in the develop branch of my fork and then make a pull request? )

For the samples, I'll try to make up a few ones :)

**Comment by adireddy** [comment]
No you just need to change the base folder to "develop" when creating the pull request.

screen shot 2015-01-16 at 14 30 35

**Comment by halfabench** [comment]
ok

**Pull request closed without merging**
