### PR TITLE
pixi-tilemap externs (v4)

### PR DESCRIPTION
**Pull request by Tiago-Ling**
- Added Shader.hx and ObjectRenderer.hx to pixi externs
- pixi-tilemap externs inside `tilemap` package;
- Added basic sample under "samples/tilemap".

### CODE REVIEW

**Comment by adireddy** [comment]
had to fix some minor issues like missing semicolons, etc but fine now.

**Comment by Tiago-Ling** [comment]
Thanks! Sorry about the semicolons and spacing, i just didn't understand why you did remove `TileRenderer.start`, `TileRenderer.destroy` and `TileRenderer.onContextChange`. Did i miss something?

**Comment by adireddy** [comment]
Those methods are already defined in the parent classes `ObjectRenderer` and `WebGLManager`

**Comment by Tiago-Ling** [comment]
Ah, ok - i didn't check the implementation :)
Just asked because i plan to make more contributions and want to avoid any mistakes in the future.

Thanks!

**Comment by adireddy** [comment]
No problem 👍

**Pull request merged**
