### PR TITLE
DisplayObject.getLocalBounds optional rect param

### PR DESCRIPTION
**Pull request by markknol**
Not sure since when this exists, but it is missing in the externs.

### CODE REVIEW

**Review by adireddy — APPROVED** [review]

**Comment by markknol** [comment]
Thanks!

**Comment by adireddy** [comment]
Not sure if there are any major updates. Will take a look when I get some time.

**Comment by markknol** [comment]
Ok haven't noticed any missing things so far too, but looks bit odd to have js and extern versions not aligned.

**Comment by adireddy** [comment]
Aligning versions don't always make sense as sometimes pixi releases just have bug fixes. If there are no changes to the externs I don't think there is a need to release just to align the versions.

**Comment by adireddy** [comment]
anyway will do another release soon :)

**Pull request merged**
