### PR TITLE
CloudKidStudios PixiParticles wrappers

### PR DESCRIPTION
**Pull request by halfabench**
New pull request to develop. Is that good?

### CODE REVIEW

**Comment by adireddy** [comment]
All Good :)

**Comment by halfabench** [comment]
Great :) Thanks!

**Comment by adireddy** [comment]
@halfabench Do you want me to release this to haxelib now or wait until we have a sample in place.

**Comment by halfabench** [comment]
Well, I'll try to add some samples this week. So It's up to you :)

**Comment by adireddy** [comment]
I know you haven't tested AnimatedParticle and I just found compiler issues with that and other classes as well.

```
pixi/plugins/particles/cloudkid/AnimatedParticle.hx:27: characters 51-52 : Unexpected )
pixi/plugins/particles/cloudkid/ParticleUtils.hx:27: characters 43-44 : Unexpected <
pixi/plugins/particles/cloudkid/ParticleUtils.hx:57: characters 15-61 : Class not found : pixi.core.Point
pixi/plugins/particles/cloudkid/ParticleUtils.hx:65: characters 15-57 : Type required for extern classes and interfaces
pixi/plugins/particles/cloudkid/PathParticle.hx:54: characters 1-28 : Type required for extern classes and interfaces
```

Don't worry I just fixed them, so please make sure you update your branch accordingly.

**Comment by adireddy** [comment]
I know it's very hard to test each and every bit of functionality in the externs but please try to a little bit careful :)

I feel that creating samples and making them part of the build will at least ensure the core functionality is always working.

Just released v2.2.3 to haxelib. http://lib.haxe.org/p/pixijs

**Comment by halfabench** [comment]
Sorry! You're absolutely right. I should have tested again that everything was ok. So I will definitely add some samples and try them before submitting updates. I'll be much more careful next time. 

Anyway thanks for the release and thanks for the good work. I really enjoy working with haxe+pixi.js. It's such a breathe :+1:

**Comment by halfabench** [comment]
Question: where do you want me to put the samples? In plugins/particles or in samples?

**Comment by adireddy** [comment]
in samples

**Comment by halfabench** [comment]
ok.

**Pull request merged**
