### PR TITLE
fix Texture.fromVideo method

### PR DESCRIPTION
**Pull request by mathieuanthoine**

### CODE REVIEW

**Comment by adireddy** [comment]
@mathieuanthoine Why do you want to change it to `String`?

there is `fromVideoUrl` method to do that.

**Comment by adireddy** [comment]
also pull request has merge conflicts, and FYI please raise pull requests against dev branch.

**Comment by mathieuanthoine** [comment]
Non fromVideo need a string too

Just check the example: 
http://pixijs.github.io/examples/index.html?s=basics&f=video.js&title=Video
It needs a String, I have made my own tests


Le 15/01/2016 10:05, Adi a écrit :
>
> @mathieuanthoine <https://github.com/mathieuanthoine> Why do you want 
> to change it to |String|?
>
> there is |fromVideoUrl| method to do that.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pixijs/pixi-haxe/pull/76#issuecomment-171906839>.
>

Mathieu

**Comment by adireddy** [comment]
No it has to be video element but the function checks if it's a string and calls `fromVideoUrl` method. 

https://github.com/pixijs/pixi.js/blob/master/src/core/textures/Texture.js#L357

**Comment by adireddy** [comment]
So in theory you should be using `fromVideoUrl` method.

**Comment by mathieuanthoine** [comment]
you're right, the pixijs' example is misleading

Thanks for clarification

Le 15/01/2016 10:11, Adi a écrit :
>
> So in theory you should be using |fromVideoUrl| method.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pixijs/pixi-haxe/pull/76#issuecomment-171908398>.
>

Mathieu

**Pull request closed without merging**
