### PR TITLE
Important fix for enums, more spine externs, Filter/RenderTarget updates

### PR DESCRIPTION
**Pull request by modjke**
Changes:
* Important: all enums changed from `extern enum` to `@:enum extern abstract` for switch statements to work
* Spine externs updated to be able to parse inlined (or staticly declared) spine data
* +Filter.autoFit
* +RenderTarget.sourceFrame to implement custom filters
* +FilterManager apply currentState typed (still allows Dynamic access)

### CODE REVIEW

**Comment by adireddy** [comment]
@modjke build failing, can u take a look pls before I merge

**Comment by modjke** [comment]
Well, it fails on extern abstract.
haxe 3.2.1 does not support it
extern abstract become a thing since 3.3.0-rc.1 (next official release after 3.2.1)
can we up requirements a bit?

**Comment by adireddy** [comment]
Not sure how many users are still on 3.2.1 and not sure if it's a good idea to force them to upgrade.

**Comment by modjke** [comment]
Currently switch statements will not work with `extern enum`, users will be forced to use if-else-if chains

**Comment by modjke** [comment]
@adireddy I can add conditionals for haxe 3.2.1, do you think this is a good idea?

**Comment by adireddy** [comment]
that would be good for backward compatibility than not supporting at all, thx @modjke

**Comment by modjke** [comment]
:heavy_check_mark:

**Pull request merged**
