### PR TITLE
Added more bindings

### PR DESCRIPTION
**Pull request by lucas-jones**

### CODE REVIEW

**Comment by adireddy** [comment]
Thanks @lucas-jones 

I know Pixi has `autoDetectRenderer` method here https://github.com/pixijs/pixi.js/blob/master/src/core/index.js but I thought this method should be part of `renderers` package and placed it there. https://github.com/pixijs/pixi-haxe/blob/master/pixi/core/renderers/Detector.hx

I borrowed `Detector` name from pixi 2 which has `autoDetectRenderer` method. 

I don't mind adding it here if you absolutely need it but it has to be duplicated as I don't want to break existing projects by removing Detector class.

Let me know your thoughts.

**Comment by lucas-jones** [comment]
Ahhh! I didn't see the Detector class. Personally I don't mind using the Detector class much better than untyped ;) But I guess it depends on how "one-to-one" you want the Haxe API -> JS API.

An option could be to add @:deprecated to the Detector class and ease people off it...

**The BaseTexture extending EventEmitter is main thing I wanted pulling**

**Comment by adireddy** [comment]
Just added BaseTexture update and released to haxelib v3.0.17.

Please use `Detector` class for now.

**Comment by lucas-jones** [comment]
Cheers!

**Pull request closed without merging**
