### PR TITLE
BlendMode enum, proper destroy(), Resource +textures +font

### PR DESCRIPTION
**Pull request by modjke**
Subj

### CODE REVIEW

**Comment by adireddy** [comment]
👍

**Comment by modjke** [comment]
Fastest merge in my life, thx! 👍

**Comment by adireddy** [comment]
:) np, out now in haxelib as well.. same version 4.4.1

**Comment by ivanpopelyshev** [comment]
What's happening? What did I miss?

**Comment by adireddy** [comment]
A few updates to the externs.. nothing much @ivanpopelyshev

**Pull request merged**
